#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Registra o autoloader do Composer.
require __DIR__.'/vendor/autoload.php';

// Inicializa o app e executa o comando do console.
$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);
